services:
  backend:
    build: .
    container_name: jobs-mail-sender
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - RESUME_PATH=/app/resume.pdf
      - SEND_EMAILS=false
      - JOB_TYPE=software
      - JOB_CATEGORY=freelance
      - JOB_LIMIT=5
      - GENERATE_MOTIVATIONAL_LETTER=true
    volumes:
      - .:/app
      - ./resume.pdf:/app/resume.pdf

  frontend:
    image: node:20
    working_dir: /app/frontend
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3001"
    ports:
      - "3001:3001"

  redis:
    image: redis:latest
    container_name: jobs-mail-sender-redis
    ports:
      - "6380:6379"